# This rule is not used by the project sgroups-k8s-netguard itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over netguard.sgroups.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sgroups-k8s-netguard
    app.kubernetes.io/managed-by: kustomize
  name: addressgroupbindingpolicy-admin-role
rules:
- apiGroups:
  - netguard.sgroups.io
  resources:
  - addressgroupbindingpolicies
  verbs:
  - '*'
- apiGroups:
  - netguard.sgroups.io
  resources:
  - addressgroupbindingpolicies/status
  verbs:
  - get
