---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - netguard.sgroups.io
  resources:
  - addressgroupbindingpolicies
  - addressgroupbindings
  - addressgroupportmappings
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netguard.sgroups.io
  resources:
  - addressgroupbindingpolicies/finalizers
  - addressgroupbindings/finalizers
  - addressgroupportmappings/finalizers
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - netguard.sgroups.io
  resources:
  - addressgroupbindingpolicies/status
  - addressgroupbindings/status
  - addressgroupportmappings/status
  - services/status
  verbs:
  - get
  - patch
  - update
