apiVersion: netguard.sgroups.io/v1alpha1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: sgroups-k8s-netguard
    app.kubernetes.io/managed-by: kustomize
  name: service-sample
spec:
  # TODO(user): Add fields here
